name: Deploy The-one-parking-bo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t theoneparking/frontend-theone  .
      - name: Publish Image to docker hub
        run: docker push theoneparking/frontend-theone:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull theoneparking/frontend-theone:latest
      - name: Delete old container
        run: docker rm -f frontend-theone-container
      - name: Run Docker Container
        run: docker run --restart=always -d -p 3003:3003 --name frontend-theone-container  theoneparking/frontend-theone
